settings:
  width: 500
  length: 500
  no_of_images: 1
  source_directory: 'C:/Users/mahee/Desktop/dead leaves project/DiffDL/source_images/forest'
  output_directory: 'C:/Users/mahee/Desktop/dead leaves project/DiffDL/generated_images/forest'
  category: 'forest'
  # category: 'beach'
  postprocess: False
  enableJax: False

params:
  rmin: 1
  rmax: 1000
  alpha: 3.0

color:

  #temporarily keeping the color scale grayscale for simplicity
  grayscale: True

  uniform_sampling: False

training:
  real_images_path: ''
  iterations: 0
  

