settings:
  width: 500
  length: 500
  no_of_images: 2
  source_directory: 'C:/Users/mahee/Desktop/dead leaves project/DiffDL/source_images/forest'
  output_directory: 'C:/Users/mahee/Desktop/dead leaves project/DiffDL/runs'
  category: 'forest'

#check random/optimal initialization values
params:
  rmin: 1
  rmax: 1000
  alpha: 3.0
  num_disks: 150000

color:
  #temporarily keeping the color scale grayscale for simplicity
  grayscale: True

  uniform_sampling: False

training:
  iterations: 2
  

